baseURL = 'https://ai-sailing.github.io/'
languageCode = 'en-us'
title = 'Sailing with AI'
theme = 'PaperMod'
publishDir = "docs"

[menu]
[[menu.main]]
name = "Resources"
url = "https://cal.com/zenja"
weight = 10
